# Generated by Django 5.2.13 on 2026-04-30 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core_operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='planningrecord',
            name='planner',
            field=models.ForeignKey(limit_choices_to={'role': 'PLANNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productionjob',
            name='parcel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_jobs', to='core_operations.roughparcel'),
        ),
        migrations.AddField(
            model_name='planningrecord',
            name='parcel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='planning', to='core_operations.roughparcel'),
        ),
        migrations.AddField(
            model_name='parceltracking',
            name='parcel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to='core_operations.roughparcel'),
        ),
        migrations.AddField(
            model_name='roughparcel',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='core_operations.supplier'),
        ),
    ]
