# Generated by Django 5.2.13 on 2026-04-30 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_operations', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolishedStone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stone_id', models.CharField(max_length=100, unique=True)),
                ('carat_weight', models.DecimalField(decimal_places=3, max_digits=10)),
                ('cut_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('color_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('clarity_grade', models.CharField(blank=True, max_length=50, null=True)),
                ('certification_number', models.CharField(blank=True, max_length=100, null=True)),
                ('certification_link', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('READY', 'Ready to Sell'), ('SOLD', 'Sold'), ('IN_TRANSIT', 'In Transit')], default='READY', max_length=50)),
                ('price_estimate', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_parcel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='polished_stones', to='core_operations.roughparcel')),
            ],
        ),
        migrations.CreateModel(
            name='YieldReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_polished_carats', models.DecimalField(decimal_places=3, max_digits=10)),
                ('breakage_carats', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('wastage_carats', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('yield_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='yield_report', to='core_operations.roughparcel')),
            ],
        ),
    ]
