# Generated by Django 5.2.13 on 2026-05-02 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_operations', '0003_polishedstone_yieldreport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningrecord',
            name='planner',
            field=models.ForeignKey(limit_choices_to={'role__in': ['PLANNER', 'ADMIN']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
