# Generated by Django 5.2.13 on 2026-05-16 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_operations', '0004_alter_planningrecord_planner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionjob',
            name='assigned_worker',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'WORKER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
