# Generated by Django 5.2.13 on 2026-05-16 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_operations', '0007_alter_supplier_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceltracking',
            name='status',
            field=models.CharField(choices=[('NEW', 'New Purchase'), ('IN_INVENTORY', 'In Inventory'), ('IN_PLANNING', 'In Planning'), ('IN_PRODUCTION', 'In Production'), ('POLISHED', 'Polished (Completed)'), ('SOLD', 'Sold')], default='NEW', max_length=50),
        ),
    ]
