# Generated by Django 5.2.13 on 2026-05-16 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core_operations', '0008_alter_parceltracking_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='planningrecord',
            name='planner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planning_assignments', to=settings.AUTH_USER_MODEL),
        ),
    ]
