# Generated by Django 5.2.13 on 2026-05-16 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_operations', '0001_initial'),
        ('core_operations', '0008_alter_parceltracking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='stone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core_operations.polishedstone'),
        ),
    ]
