# Generated by Django 5.2.13 on 2026-04-30 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin / Owner'), ('OFFICE', 'Office / Admin'), ('INVENTORY', 'Inventory / Admin'), ('PLANNER', 'Planner'), ('PRODUCTION_MANAGER', 'Production Manager'), ('SUPERVISOR', 'Supervisor'), ('WORKER', 'Worker'), ('SALES', 'Sales / Inventory'), ('ACCOUNTANT', 'Accountant')], default='OFFICE', max_length=50),
        ),
        migrations.CreateModel(
            name='WorkerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(blank=True, help_text='Comma separated skills, e.g., Sawing, Polishing', max_length=255, null=True)),
                ('efficiency_score', models.DecimalField(decimal_places=2, default=100.0, help_text='Efficiency percentage', max_digits=5)),
                ('user', models.OneToOneField(limit_choices_to={'role': 'WORKER'}, on_delete=django.db.models.deletion.CASCADE, related_name='worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
